version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: userLocal
      POSTGRES_PASSWORD: senhaLocal
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local-api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devdb
      SPRING_DATASOURCE_USERNAME: userLocal
      SPRING_DATASOURCE_PASSWORD: senhaLocal
      BOOLEAN_SQL: "true"
      JWT_SECRET: Q^F9m4n+BMzPQBh!C5Bk
      SUPABASE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nY3BuZWxlYXlmdmdiaWtkamNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDAzNTAsImV4cCI6MjA3NDM3NjM1MH0._N1Z7zq5rq5zuzNG_O-C3xnr2azv4Fus9zWCCkFR5J0
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
