spring.application.name=api-know-hall

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.jpa.hibernate.ddl-auto= none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Config da JWT
jwt.secret=${JWT_SECRET}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/knowhall.changelog-master.xml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.liquibase.drop-first=false
